repo: "http://bigtop01.cloudera.org:8080/view/Releases/job/Bigtop-0.8.0/label=centos6/6/artifact/output/"
num_instances: 3
distro: centos
components: [hadoop, yarn,hive,mahout]
enable_local_repo: false
run_smoke_tests: false
smoke_test_components: [mapreduce,pig,mahout,hive]
jdk: "java-1.7.0-openjdk-devel.x86_64"
keypair_name: ""
key_path: "" 
FQDN: ""

